### ISSUE TITLE
Able to connect to S700 Scanner when removing app permissions through device settings

### ISSUE THREAD

**Issue by ray-predictspring** [SocketMobile/cocoapods-capturesdk#8]
Hi.

Steps:

1.Launch app
2.Connect Bluetooth socket to app (verify you are able to scan)
3.Device Setting-> POS app -> Disable Bluetooth permission. 
4.Kill and relaunch the app

Actual : The socket connects to the app

We went through our code and we are not getting any error for the connection to happen after the Bluetooth permissions have been disabled for our app in the device settings (thus, we are connecting correctly). This is the result of our initialization:

<img width="1305" alt="Screen Shot 2023-09-07 at 12 39 48 PM" src="https://github.com/SocketMobile/cocoapods-capturesdk/assets/110852641/8b79d10f-e61a-4a2d-9f25-f402d7a59f0a">

And this is the delegate call we receive containing the previously connected device.

<img width="1299" alt="Screen Shot 2023-09-07 at 12 59 00 PM" src="https://github.com/SocketMobile/cocoapods-capturesdk/assets/110852641/b9fed344-0142-40bc-ae2d-e7efda401382">

Note that in both places, we don'e get an error indicating the permissions disabling on the device

After the connection happens, we are able to scan using the device and get responses from the data retrieved. 

Is this expected?

As a side note, checking the companion app, we do see that the scanner status changes when the permissions are disabled for it

<img width="345" alt="Screen Shot 2023-09-07 at 13 02 48 PM" src="https://github.com/SocketMobile/cocoapods-capturesdk/assets/110852641/9f39df91-298c-4d69-ac75-2a119c9faf8d">

Scanner: **S700**, 
SDK version: **1.7.11.64**
OS Version **iPad OS 15.5**

**Comment by cyrille-socket** [comment]
Hi @ray-predictspring 

so the S700 is a Bluetooth Classic scanner so it is not handled by the bluetooth permissions. Those permissions are for Bluetooth Low Energy only from iOS13. So that's normal if you disabled the permissions that the scanner still connects. The SDK is just getting the list of Bluetooth Classic devices from the External Accessory Framework from iOS but we don't manage the connection nor the permissions.

For the Bluetooth Low Energy then, we will make a fix to manage in a proper way the permissions.

Best,
Cyrille

**Comment by ray-predictspring** [comment]
HI @cyrille-socket !

Thanks for the response.
